version: '3.8'
services:
  app:
      environment:
        - MONGODB_URI=mongodb://localhost:27017/website-analyzer
        - PORT=3000
        - NODE_TLS_REJECT_UNAUTHORIZED=0
        - DNS_SERVERS=8.8.8.8,1.1.1.1
      ports:
        - "3000:3000"
      dns:
        - 8.8.8.8
        - 1.1.1.1
      extra_hosts:
        - "host.docker.internal:host-gateway"
      depends_on:
        - mongodb
      build:
          context: .
          dockerfile: Dockerfile
        
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongodb


volumes:
  mongodb_data: